/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLiderRouteImport } from './routes/_authenticated/lider'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin.calendario'
import { Route as AuthenticatedAdminEntidadesRouteImport } from './routes/_authenticated/admin.entidades'
import { Route as AuthenticatedAdminReservasRouteImport } from './routes/_authenticated/admin.reservas'
import { Route as AuthenticatedAdminSalasRouteImport } from './routes/_authenticated/admin.salas'
import { Route as AuthenticatedLiderIndexRouteImport } from './routes/_authenticated/lider.index'
import { Route as AuthenticatedLiderCalendarioRouteImport } from './routes/_authenticated/lider.calendario'
import { Route as AuthenticatedLiderEquipeRouteImport } from './routes/_authenticated/lider.equipe'
import { Route as AuthenticatedLiderReservasRouteImport } from './routes/_authenticated/lider.reservas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiderRoute = AuthenticatedLiderRouteImport.update({
  id: '/lider',
  path: '/lider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntidadesRoute =
  AuthenticatedAdminEntidadesRouteImport.update({
    id: '/entidades',
    path: '/entidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReservasRoute =
  AuthenticatedAdminReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalasRoute = AuthenticatedAdminSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedLiderIndexRoute = AuthenticatedLiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLiderRoute,
} as any)
const AuthenticatedLiderCalendarioRoute =
  AuthenticatedLiderCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedLiderRoute,
  } as any)
const AuthenticatedLiderEquipeRoute =
  AuthenticatedLiderEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedLiderRoute,
  } as any)
const AuthenticatedLiderReservasRoute =
  AuthenticatedLiderReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedLiderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/lider': typeof AuthenticatedLiderRouteWithChildren
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/entidades': typeof AuthenticatedAdminEntidadesRoute
  '/admin/reservas': typeof AuthenticatedAdminReservasRoute
  '/admin/salas': typeof AuthenticatedAdminSalasRoute
  '/lider/calendario': typeof AuthenticatedLiderCalendarioRoute
  '/lider/equipe': typeof AuthenticatedLiderEquipeRoute
  '/lider/reservas': typeof AuthenticatedLiderReservasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lider/': typeof AuthenticatedLiderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/entidades': typeof AuthenticatedAdminEntidadesRoute
  '/admin/reservas': typeof AuthenticatedAdminReservasRoute
  '/admin/salas': typeof AuthenticatedAdminSalasRoute
  '/lider/calendario': typeof AuthenticatedLiderCalendarioRoute
  '/lider/equipe': typeof AuthenticatedLiderEquipeRoute
  '/lider/reservas': typeof AuthenticatedLiderReservasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lider': typeof AuthenticatedLiderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/lider': typeof AuthenticatedLiderRouteWithChildren
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/entidades': typeof AuthenticatedAdminEntidadesRoute
  '/_authenticated/admin/reservas': typeof AuthenticatedAdminReservasRoute
  '/_authenticated/admin/salas': typeof AuthenticatedAdminSalasRoute
  '/_authenticated/lider/calendario': typeof AuthenticatedLiderCalendarioRoute
  '/_authenticated/lider/equipe': typeof AuthenticatedLiderEquipeRoute
  '/_authenticated/lider/reservas': typeof AuthenticatedLiderReservasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/lider/': typeof AuthenticatedLiderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/lider'
    | '/admin/calendario'
    | '/admin/entidades'
    | '/admin/reservas'
    | '/admin/salas'
    | '/lider/calendario'
    | '/lider/equipe'
    | '/lider/reservas'
    | '/admin/'
    | '/lider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/calendario'
    | '/admin/entidades'
    | '/admin/reservas'
    | '/admin/salas'
    | '/lider/calendario'
    | '/lider/equipe'
    | '/lider/reservas'
    | '/admin'
    | '/lider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/lider'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/entidades'
    | '/_authenticated/admin/reservas'
    | '/_authenticated/admin/salas'
    | '/_authenticated/lider/calendario'
    | '/_authenticated/lider/equipe'
    | '/_authenticated/lider/reservas'
    | '/_authenticated/admin/'
    | '/_authenticated/lider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lider': {
      id: '/_authenticated/lider'
      path: '/lider'
      fullPath: '/lider'
      preLoaderRoute: typeof AuthenticatedLiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entidades': {
      id: '/_authenticated/admin/entidades'
      path: '/entidades'
      fullPath: '/admin/entidades'
      preLoaderRoute: typeof AuthenticatedAdminEntidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reservas': {
      id: '/_authenticated/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AuthenticatedAdminReservasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/salas': {
      id: '/_authenticated/admin/salas'
      path: '/salas'
      fullPath: '/admin/salas'
      preLoaderRoute: typeof AuthenticatedAdminSalasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/lider/': {
      id: '/_authenticated/lider/'
      path: '/'
      fullPath: '/lider/'
      preLoaderRoute: typeof AuthenticatedLiderIndexRouteImport
      parentRoute: typeof AuthenticatedLiderRoute
    }
    '/_authenticated/lider/calendario': {
      id: '/_authenticated/lider/calendario'
      path: '/calendario'
      fullPath: '/lider/calendario'
      preLoaderRoute: typeof AuthenticatedLiderCalendarioRouteImport
      parentRoute: typeof AuthenticatedLiderRoute
    }
    '/_authenticated/lider/equipe': {
      id: '/_authenticated/lider/equipe'
      path: '/equipe'
      fullPath: '/lider/equipe'
      preLoaderRoute: typeof AuthenticatedLiderEquipeRouteImport
      parentRoute: typeof AuthenticatedLiderRoute
    }
    '/_authenticated/lider/reservas': {
      id: '/_authenticated/lider/reservas'
      path: '/reservas'
      fullPath: '/lider/reservas'
      preLoaderRoute: typeof AuthenticatedLiderReservasRouteImport
      parentRoute: typeof AuthenticatedLiderRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminEntidadesRoute: typeof AuthenticatedAdminEntidadesRoute
  AuthenticatedAdminReservasRoute: typeof AuthenticatedAdminReservasRoute
  AuthenticatedAdminSalasRoute: typeof AuthenticatedAdminSalasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminEntidadesRoute: AuthenticatedAdminEntidadesRoute,
  AuthenticatedAdminReservasRoute: AuthenticatedAdminReservasRoute,
  AuthenticatedAdminSalasRoute: AuthenticatedAdminSalasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLiderRouteChildren {
  AuthenticatedLiderCalendarioRoute: typeof AuthenticatedLiderCalendarioRoute
  AuthenticatedLiderEquipeRoute: typeof AuthenticatedLiderEquipeRoute
  AuthenticatedLiderReservasRoute: typeof AuthenticatedLiderReservasRoute
  AuthenticatedLiderIndexRoute: typeof AuthenticatedLiderIndexRoute
}

const AuthenticatedLiderRouteChildren: AuthenticatedLiderRouteChildren = {
  AuthenticatedLiderCalendarioRoute: AuthenticatedLiderCalendarioRoute,
  AuthenticatedLiderEquipeRoute: AuthenticatedLiderEquipeRoute,
  AuthenticatedLiderReservasRoute: AuthenticatedLiderReservasRoute,
  AuthenticatedLiderIndexRoute: AuthenticatedLiderIndexRoute,
}

const AuthenticatedLiderRouteWithChildren =
  AuthenticatedLiderRoute._addFileChildren(AuthenticatedLiderRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLiderRoute: typeof AuthenticatedLiderRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLiderRoute: AuthenticatedLiderRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
