// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { SEED_PROJECTS } from "@/lib/seed-projects";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

type TableMap = {
  admin_messages: Database["public"]["Tables"]["admin_messages"]["Row"];
  entities: Database["public"]["Tables"]["entities"]["Row"];
  events: Database["public"]["Tables"]["events"]["Row"];
  general_meetings: Database["public"]["Tables"]["general_meetings"]["Row"];
  leader_requests: Database["public"]["Tables"]["leader_requests"]["Row"];
  meeting_attendances: Database["public"]["Tables"]["meeting_attendances"]["Row"];
  members: Database["public"]["Tables"]["members"]["Row"];
  peer_workshops: Database["public"]["Tables"]["peer_workshops"]["Row"];
  profiles: Database["public"]["Tables"]["profiles"]["Row"];
  reservations: Database["public"]["Tables"]["reservations"]["Row"];
  reward_redemptions: Database["public"]["Tables"]["reward_redemptions"]["Row"];
  rooms: Database["public"]["Tables"]["rooms"]["Row"];
  staff_calls: Database["public"]["Tables"]["staff_calls"]["Row"];
  staff_volunteers: Database["public"]["Tables"]["staff_volunteers"]["Row"];
  training_registrations: Database["public"]["Tables"]["training_registrations"]["Row"];
  trainings: Database["public"]["Tables"]["trainings"]["Row"];
  user_roles: Database["public"]["Tables"]["user_roles"]["Row"];
};

const STORAGE_DB_KEY = "liga_uni_demo_db_v18";
const STORAGE_USER_KEY = "liga_uni_demo_user_v18";

function createInitialDb(): { [K in keyof TableMap]: TableMap[K][] } {
  const now = new Date().toISOString();
  const inDays = (days: number, hours: number) => {
    const d = new Date();
    d.setDate(d.getDate() + days);
    d.setHours(hours, 0, 0, 0);
    return d.toISOString();
  };

  return {
    profiles: [
      ...SEED_PROJECTS.map((p) => ({
        id: p.leaderId,
        nome: p.leaderNome,
        email: p.leaderEmail,
        created_at: now,
      })),
      {
        id: "user-admin-1",
        nome: "Administrador Ágora",
        email: "admin.teste@example.com",
        created_at: now,
      },
    ],
    user_roles: [
      ...SEED_PROJECTS.map((p, idx) => ({
        id: `role-leader-${idx + 1}`,
        user_id: p.leaderId,
        role: "leader" as const,
      })),
      { id: "role-admin-1", user_id: "user-admin-1", role: "admin" },
    ],
    entities: SEED_PROJECTS.map((p) => ({
      id: p.id,
      nome: p.nome,
      descricao: p.descricao,
      leader_id: p.leaderId,
      avisos_email: true,
      created_at: now,
    })),
    leader_requests: [
      {
        id: "req-1",
        user_id: "user-pending-1",
        nome_lider: "Mateus Henrique",
        email: "mateus.aero@edu.udesc.br",
        faculdade: "UDESC Joinville",
        projeto: "Liga Acadêmica de Engenharia Aeroespacial",
        descricao:
          "Grupo voltado ao estudo de propulsão, aerodinâmica e microssatélites no CCT/UDESC Joinville.",
        status: "pending",
        admin_note: null,
        created_at: now,
      },
    ],
    members: SEED_PROJECTS.flatMap((p) =>
      p.members.map((m) => ({
        id: m.id,
        entity_id: p.id,
        nome: m.nome,
        email: m.email,
        curso: m.curso,
        created_at: now,
      })),
    ),
    rooms: [
      {
        id: "room-1",
        nome: "Sala de Reunião A",
        capacidade: 12,
        descricao: "Sala equipada com TV e quadro branco no Ágora Tech Park.",
        ativa: true,
        created_at: now,
      },
      {
        id: "room-2",
        nome: "Sala de Reunião B",
        capacidade: 20,
        descricao: "Espaço colaborativo para dinâmicas e reuniões de projetos.",
        ativa: true,
        created_at: now,
      },
      {
        id: "room-3",
        nome: "Auditório Ágora Tech Park",
        capacidade: 80,
        descricao: "Auditório principal para capacitações, workshops, mostras e hackathons.",
        ativa: true,
        created_at: now,
      },
      {
        id: "room-4",
        nome: "Sala compartilhada Ágora.Share",
        capacidade: 30,
        descricao: "Espaço compartilhado de coworking e integração entre equipes no Ágora.Share.",
        ativa: true,
        created_at: now,
      },
    ],
    events: [
      {
        id: "ev-1",
        entity_id: "ent-1",
        titulo: "Oficina de Robótica Móvel e Inclusão Social",
        descricao:
          "Atividade prática do GERM aberta à comunidade para fomentar o interesse em ciência e tecnologia.",
        local: "Sala de Reunião A",
        inicio: inDays(2, 14),
        fim: inDays(2, 16),
        created_at: now,
      },
      {
        id: "ev-2",
        entity_id: "ent-1",
        titulo: "Mostra e Hackathon de Robótica no Ágora",
        descricao:
          "Imersão de dois dias com discentes do CCT/UDESC apresentando projetos de robótica móvel.",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(5, 9),
        fim: inDays(6, 18),
        created_at: now,
      },
      {
        id: "ev-3",
        entity_id: "ent-1",
        titulo: "Reunião Geral do GERM — UDESC Joinville",
        descricao:
          "Alinhamento das frentes de ensino, pesquisa e extensão dos cursos do Centro de Ciências Tecnológicas.",
        local: "Sala de Reunião B",
        inicio: inDays(10, 19),
        fim: inDays(10, 21),
        created_at: now,
      },
      {
        id: "ev-4",
        entity_id: "ent-2",
        titulo: "Apresentação dos Protótipos IC e EV — Fórmula CEM",
        descricao:
          "Demonstração técnica dos veículos Fórmula-SAE a combustão e elétrico desenvolvidos na UFSC Joinville.",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(4, 15),
        fim: inDays(4, 18),
        created_at: now,
      },
      {
        id: "ev-5",
        entity_id: "ent-2",
        titulo: "Revisão de Projeto para Competição SAE Brasil",
        descricao:
          "Reunião dos subsistemas de powertrain, aerodinâmica e eletrônica da equipe Fórmula CEM.",
        local: "Sala compartilhada Ágora.Share",
        inicio: inDays(8, 14),
        fim: inDays(8, 17),
        created_at: now,
      },
    ],
    reservations: [
      {
        id: "res-1",
        entity_id: "ent-1",
        event_id: "ev-1",
        room_id: "room-1",
        requested_by: "user-leader-1",
        purpose: "capacitacao_geral",
        motivo: "Realização da Oficina de Robótica Móvel e Inclusão Social pelo GERM (UDESC)",
        inicio: inDays(2, 14),
        fim: inDays(2, 16),
        status: "approved",
        admin_note: null,
        created_at: now,
      },
      {
        id: "res-2",
        entity_id: "ent-1",
        event_id: "ev-3",
        room_id: "room-2",
        requested_by: "user-leader-1",
        purpose: "reuniao_projeto",
        motivo: "Reunião Geral da equipe do GERM — UDESC Joinville",
        inicio: inDays(10, 19),
        fim: inDays(10, 21),
        status: "pending",
        admin_note: null,
        created_at: now,
      },
      {
        id: "res-3",
        entity_id: "ent-2",
        event_id: "ev-4",
        room_id: "room-3",
        requested_by: "user-leader-2",
        purpose: "capacitacao_geral",
        motivo: "Apresentação dos Protótipos IC e EV da Fórmula CEM (UFSC Joinville)",
        inicio: inDays(4, 15),
        fim: inDays(4, 18),
        status: "approved",
        admin_note: null,
        created_at: now,
      },
      {
        id: "res-4",
        entity_id: "ent-2",
        event_id: "ev-5",
        room_id: "room-2",
        requested_by: "user-leader-2",
        purpose: "reuniao_projeto",
        motivo: "Revisão de Projeto para Competição SAE Brasil — Fórmula CEM (UFSC)",
        inicio: inDays(8, 14),
        fim: inDays(8, 17),
        status: "pending",
        admin_note: null,
        created_at: now,
      },
    ],
    trainings: [
      {
        id: "tr-1",
        titulo: "Capacitação em Comunicação Proativa e Liderança Colaborativa",
        descricao:
          "Desenvolva habilidades de comunicação assertiva, alinhamento de expectativas em equipes universitárias, resolução de conflitos e protagonismo nos projetos do Liga UNI.",
        ministrante: "Equipe Liga Ágora · Mentoria de Gestão",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(3, 18),
        fim: inDays(3, 20),
        vagas: 40,
        ativa: true,
        created_at: now,
      },
      {
        id: "tr-2",
        titulo: "Gestão Ágil de Projetos Acadêmicos e Captação de Parcerias",
        descricao:
          "Boas práticas de organização de sprints, gestão de membros voluntários e estruturação de propostas de patrocínio para equipes de competição e extensão.",
        ministrante: "Comunidade Ágora Tech Park",
        local: "Sala de Reunião B",
        inicio: inDays(7, 19),
        fim: inDays(7, 21),
        vagas: 25,
        ativa: true,
        created_at: now,
      },
      {
        id: "tr-3",
        titulo: "Pitch de Alto Impacto e Apresentação de Protótipos",
        descricao:
          "Como apresentar os resultados técnicos da sua equipe para avaliadores, empresas parceiras e comunidade em 3 a 5 minutos.",
        ministrante: "Mentores Liga Ágora",
        local: "Sala de Reunião A",
        inicio: inDays(12, 18),
        fim: inDays(12, 20),
        vagas: 20,
        ativa: true,
        created_at: now,
      },
      {
        id: "tr-past-1",
        titulo: "Boas-Vindas e Integração de Líderes Liga UNI",
        descricao:
          "Encontro formativo inicial sobre cultura de inovação colaborativa e uso compartilhado dos espaços do Ágora Tech Park.",
        ministrante: "Coordenação Liga Ágora",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(-10, 18),
        fim: inDays(-10, 20),
        vagas: 50,
        ativa: true,
        created_at: now,
      },
    ],
    training_registrations: [
      {
        id: "treg-1",
        training_id: "tr-1",
        entity_id: "ent-1",
        participantes: "Carlos Eduardo, Beatriz Souza, Rafael Mendes",
        moedas_liberadas: false,
        created_at: now,
      },
      {
        id: "treg-past-1",
        training_id: "tr-past-1",
        entity_id: "ent-1",
        participantes: "Carlos Eduardo, Beatriz Souza",
        moedas_liberadas: true,
        created_at: now,
      },
      {
        id: "treg-2",
        training_id: "tr-1",
        entity_id: "ent-2",
        participantes: "Lucas Ferreira, Mariana Alves",
        moedas_liberadas: false,
        created_at: now,
      },
    ],
    staff_calls: [
      {
        id: "sc-1",
        evento: "Hackathon Liga UNI & Mostra Tecnológica no Ágora",
        descricao:
          "Precisamos de voluntários das entidades para apoio no credenciamento, recepção dos participantes, orientação de salas e suporte de palco durante o evento no Ágora Tech Park.",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(5, 8),
        fim: inDays(5, 18),
        vagas: 15,
        ativa: true,
        created_at: now,
      },
      {
        id: "sc-2",
        evento: "Encontro de Integração Universidade-Empresa (Liga Ágora)",
        descricao:
          "Apoio como staff na organização das rodadas de conexão entre grupos estudantis universitários e empresas residentes do Ágora.",
        local: "Sala compartilhada Ágora.Share",
        inicio: inDays(9, 14),
        fim: inDays(9, 19),
        vagas: 10,
        ativa: true,
        created_at: now,
      },
      {
        id: "sc-3",
        evento: "Dia da Comunidade: Robótica e Engenharias para Escolas",
        descricao:
          "Auxílio na monitoria de visitantes, organização das bancadas de exposição dos protótipos e acompanhamento de turmas escolares.",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(14, 9),
        fim: inDays(14, 17),
        vagas: 20,
        ativa: true,
        created_at: now,
      },
      {
        id: "sc-past-1",
        evento: "Recepção de Calouros & Tour de Inovação no Ágora",
        descricao:
          "Apoio das entidades estudantis na recepção e apresentação dos laboratórios e espaços para novos estudantes universitários.",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(-14, 14),
        fim: inDays(-14, 18),
        vagas: 12,
        ativa: true,
        created_at: now,
      },
    ],
    staff_volunteers: [
      {
        id: "sv-1",
        call_id: "sc-1",
        entity_id: "ent-1",
        participantes: "Carlos Eduardo, Juliana Costa",
        observacao: "Disponibilidade para recepção e suporte às equipes de robótica.",
        moedas_liberadas: false,
        created_at: now,
      },
      {
        id: "sv-past-1",
        call_id: "sc-past-1",
        entity_id: "ent-1",
        participantes: "Rafael Mendes, Juliana Costa",
        observacao: "Apoio na condução dos grupos pelo Ágora.",
        moedas_liberadas: true,
        created_at: now,
      },
      {
        id: "sv-2",
        call_id: "sc-1",
        entity_id: "ent-2",
        participantes: "Gabriel Rocha, Fernanda Lima",
        observacao: "Apoio na montagem de estandes e credenciamento.",
        moedas_liberadas: false,
        created_at: now,
      },
    ],
    peer_workshops: [
      {
        id: "pw-1",
        entity_id: "ent-1",
        room_id: "room-3",
        titulo: "Introdução a ROS2 e Sensores para Robótica Móvel",
        descricao:
          "Oficina prática aberta para todas as equipes sobre integração de sensores e navegação autônoma com ROS2.",
        ministrantes: "Rafael Mendes, Carlos Eduardo",
        em_conjunto: false,
        partner_entity_id: null,
        data_sugerida: inDays(6, 15),
        fim: inDays(6, 17),
        status: "approved",
        moedas_liberadas: false,
        created_at: now,
      },
      {
        id: "pw-past-1",
        entity_id: "ent-1",
        room_id: "room-1",
        titulo: "Modelagem CAD 3D e Impressão Rápida de Protótipos",
        descricao:
          "Oficina ministrada pela equipe sobre boas práticas de fatiamento e resistência mecânica em peças impressas em 3D.",
        ministrantes: "Beatriz Souza, Rafael Mendes",
        em_conjunto: false,
        partner_entity_id: null,
        data_sugerida: inDays(-8, 15),
        fim: inDays(-8, 17),
        status: "approved",
        moedas_liberadas: true,
        created_at: now,
      },
      {
        id: "pw-2",
        entity_id: "ent-2",
        room_id: "room-4",
        titulo: "Telemetria e Aquisição de Dados em Protótipos de Competição",
        descricao:
          "Compartilhamento de práticas da Fórmula CEM sobre instrumentação eletrônica e análise de dados em pista.",
        ministrantes: "Mariana Alves, Lucas Ferreira",
        em_conjunto: false,
        partner_entity_id: null,
        data_sugerida: inDays(11, 16),
        fim: inDays(11, 18),
        status: "pending",
        moedas_liberadas: false,
        created_at: now,
      },
    ],
    general_meetings: [
      {
        id: "gm-1",
        titulo: "1ª Reunião Geral de Alinhamento Liga UNI — Semestre 2026/2",
        pauta:
          "Apresentação oficial do calendário de eventos do semestre no Ágora Tech Park, regras de uso das salas, distribuição de estandes na Mostra Tecnológica e integração entre os líderes das entidades universitárias.",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(4, 19),
        fim: inDays(4, 21),
        pontos: 75,
        obrigatoria: true,
        ativa: true,
        created_at: now,
      },
      {
        id: "gm-2",
        titulo: "Assembleia Geral de Líderes & Planejamento do Hackathon Liga UNI",
        pauta:
          "Definição das comissões organizadoras entre as entidades, sorteio de horários de apresentação e alinhamento com mentores do Liga Ágora.",
        local: "Sala compartilhada Ágora.Share",
        inicio: inDays(15, 19),
        fim: inDays(15, 21),
        pontos: 75,
        obrigatoria: true,
        ativa: true,
        created_at: now,
      },
      {
        id: "gm-past-1",
        titulo: "Reunião de Abertura do Semestre Liga UNI",
        pauta:
          "Recepção das entidades veteranas e novas, alinhamento das diretrizes de convivência e apresentação do sistema LigaCoins.",
        local: "Auditório Ágora Tech Park",
        inicio: inDays(-12, 19),
        fim: inDays(-12, 21),
        pontos: 75,
        obrigatoria: true,
        ativa: true,
        created_at: now,
      },
    ],
    meeting_attendances: [
      {
        id: "ma-1",
        meeting_id: "gm-1",
        entity_id: "ent-1",
        representantes: "Carlos Eduardo, Beatriz Souza",
        presente: true,
        moedas_liberadas: false,
        created_at: now,
      },
      {
        id: "ma-past-1",
        meeting_id: "gm-past-1",
        entity_id: "ent-1",
        representantes: "Carlos Eduardo, Beatriz Souza",
        presente: true,
        moedas_liberadas: true,
        created_at: now,
      },
      {
        id: "ma-2",
        meeting_id: "gm-1",
        entity_id: "ent-2",
        representantes: "Lucas Ferreira",
        presente: true,
        moedas_liberadas: false,
        created_at: now,
      },
    ],
    admin_messages: [
      {
        id: "msg-1",
        entity_id: "ent-1",
        topico: "Salas & Equipamentos",
        assunto: "Dúvida sobre equipamentos do Auditório Ágora",
        mensagem:
          "Olá! Gostaríamos de saber se o auditório possui adaptador HDMI e microfone sem fio para nossa oficina de robótica.",
        resposta:
          "Sim! O auditório já conta com 2 microfones sem fio, passador de slides e cabo HDMI na bancada principal.",
        status: "answered",
        created_at: now,
      },
      {
        id: "msg-2",
        entity_id: "ent-2",
        topico: "LigaCoins & Benefícios",
        assunto: "Agendamento de Mentoria Técnica",
        mensagem:
          "Gostaríamos de alinhar qual empresa residente do Ágora poderia nos apoiar na revisão da telemetria elétrica.",
        resposta: null,
        status: "pending",
        created_at: now,
      },
    ],
    reward_redemptions: [
      {
        id: "red-1",
        entity_id: "ent-1",
        recompensa_id: "mentoria-empresa",
        recompensa_titulo: "Mentoria VIP com Empresa Residente do Ágora",
        custo: 100,
        observacao: "Interesse em mentoria de visão computacional e sistemas embarcados.",
        status: "pending",
        created_at: now,
      },
    ],
  };
}

function loadPersistedDb(): { [K in keyof TableMap]: TableMap[K][] } {
  const initial = createInitialDb();
  if (typeof window !== "undefined") {
    try {
      const raw = window.localStorage.getItem(STORAGE_DB_KEY);
      if (raw) {
        const parsed = JSON.parse(raw) as Partial<{ [K in keyof TableMap]: TableMap[K][] }>;
        return {
          profiles: Array.isArray(parsed.profiles) ? parsed.profiles : initial.profiles,
          user_roles: Array.isArray(parsed.user_roles) ? parsed.user_roles : initial.user_roles,
          entities: Array.isArray(parsed.entities) ? parsed.entities : initial.entities,
          leader_requests: Array.isArray(parsed.leader_requests)
            ? parsed.leader_requests
            : initial.leader_requests,
          members: Array.isArray(parsed.members) ? parsed.members : initial.members,
          rooms: Array.isArray(parsed.rooms) ? parsed.rooms : initial.rooms,
          events: Array.isArray(parsed.events) ? parsed.events : initial.events,
          reservations: Array.isArray(parsed.reservations)
            ? parsed.reservations
            : initial.reservations,
          trainings: Array.isArray(parsed.trainings) ? parsed.trainings : initial.trainings,
          training_registrations: Array.isArray(parsed.training_registrations)
            ? parsed.training_registrations
            : initial.training_registrations,
          staff_calls: Array.isArray(parsed.staff_calls)
            ? parsed.staff_calls
            : initial.staff_calls,
          staff_volunteers: Array.isArray(parsed.staff_volunteers)
            ? parsed.staff_volunteers
            : initial.staff_volunteers,
          peer_workshops: Array.isArray(parsed.peer_workshops)
            ? parsed.peer_workshops
            : initial.peer_workshops,
          general_meetings: Array.isArray(parsed.general_meetings)
            ? parsed.general_meetings
            : initial.general_meetings,
          meeting_attendances: Array.isArray(parsed.meeting_attendances)
            ? parsed.meeting_attendances
            : initial.meeting_attendances,
          admin_messages: Array.isArray(parsed.admin_messages)
            ? parsed.admin_messages
            : initial.admin_messages,
          reward_redemptions: Array.isArray(parsed.reward_redemptions)
            ? parsed.reward_redemptions
            : initial.reward_redemptions,
        };
      }
    } catch {
      // ignore
    }
  }
  savePersistedDb(initial);
  return initial;
}

function savePersistedDb(db: { [K in keyof TableMap]: TableMap[K][] }) {
  if (typeof window !== "undefined") {
    try {
      window.localStorage.setItem(STORAGE_DB_KEY, JSON.stringify(db));
    } catch {
      // ignore
    }
  }
}

type DemoUser = { id: string; email: string; user_metadata?: Record<string, unknown> };

function loadPersistedUser(): DemoUser | null {
  if (typeof window !== "undefined") {
    try {
      const raw = window.localStorage.getItem(STORAGE_USER_KEY);
      if (raw) return JSON.parse(raw) as DemoUser;
    } catch {
      // ignore
    }
  }
  return null;
}

function savePersistedUser(user: DemoUser | null) {
  if (typeof window !== "undefined") {
    try {
      if (user) window.localStorage.setItem(STORAGE_USER_KEY, JSON.stringify(user));
      else window.localStorage.removeItem(STORAGE_USER_KEY);
    } catch {
      // ignore
    }
  }
}

function createMockSupabaseClient() {
  const dayMs = 86400000;
  const db = loadPersistedDb();
  let currentUser: DemoUser | null = loadPersistedUser();
  const listeners = new Set<(event: string, session: unknown) => void>();

  function notify(event: string) {
    const session = currentUser ? { user: currentUser, access_token: "mock-token" } : null;
    listeners.forEach((cb) => cb(event, session));
  }

  function buildQuery(table: keyof TableMap) {
    const filters: Array<(row: Record<string, unknown>) => boolean> = [];
    let orderCol: string | null = null;
    let orderAsc = true;
    let op: "select" | "insert" | "update" | "delete" = "select";
    let payload: unknown = null;
    let isMaybeSingle = false;

    const execute = async () => {
      if (!Array.isArray(db[table])) {
        (db as Record<string, unknown[]>)[table] = [];
      }
      const list = db[table] as Record<string, unknown>[];
      if (op === "insert") {
        const items = Array.isArray(payload) ? payload : [payload];
        const inserted = items.map((item) => {
          const row = {
            id: `${table}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
            created_at: new Date().toISOString(),
            ...(table === "reservations" ? { status: "pending", admin_note: null } : {}),
            ...(item as Record<string, unknown>),
          };
          list.push(row);
          return row;
        });
        savePersistedDb(db);
        return { data: isMaybeSingle ? (inserted[0] ?? null) : inserted, error: null };
      }

      const matched = list.filter((r) => filters.every((f) => f(r)));

      if (op === "update") {
        if (table === "leader_requests" && payload && typeof payload === "object") {
          const upd = payload as Record<string, unknown>;
          for (const r of matched) {
            const nextStatus = (upd["status"] ?? r["status"]) as string;
            const reqUserId = String(r["user_id"]);
            const reqNome = String(r["nome_lider"]);
            const reqEmail = String(r["email"]);
            const reqFaculdade = String(r["faculdade"]);
            const reqProjeto = String(r["projeto"]);
            const reqDescricao = String(r["descricao"] ?? "");

            if (nextStatus === "approved") {
              if (!db.profiles.some((p) => p.id === reqUserId)) {
                db.profiles.push({
                  id: reqUserId,
                  nome: reqNome,
                  email: reqEmail,
                  created_at: new Date().toISOString(),
                });
              }
              if (!db.user_roles.some((ur) => ur.user_id === reqUserId)) {
                db.user_roles.push({
                  id: `role-${Date.now()}`,
                  user_id: reqUserId,
                  role: "leader",
                });
              }
              if (!db.entities.some((ent) => ent.leader_id === reqUserId)) {
                const entityName = reqFaculdade
                  ? `${reqProjeto} (${reqFaculdade})`
                  : reqProjeto;
                db.entities.push({
                  id: `ent-${Date.now()}`,
                  nome: entityName,
                  descricao: reqDescricao,
                  leader_id: reqUserId,
                  created_at: new Date().toISOString(),
                });
              }
            }
          }
        }
        if (table === "peer_workshops" && payload && typeof payload === "object") {
          const upd = payload as Record<string, unknown>;
          for (const r of matched) {
            const nextStatus = (upd["status"] ?? r["status"]) as string;
            if (nextStatus === "approved") {
              const titulo = String(r["titulo"]);
              const roomObj = db.rooms.find((rm) => rm.id === r["room_id"]);
              const roomName = roomObj?.nome ?? "Auditório Ágora Tech Park";
              if (!db.trainings.some((t) => t.titulo === titulo)) {
                const startIso = String(r["data_sugerida"] || new Date().toISOString());
                const endIso = r["fim"]
                  ? String(r["fim"])
                  : new Date(new Date(startIso).getTime() + 2 * 3600000).toISOString();
                db.trainings.push({
                  id: `tr-${Date.now()}`,
                  titulo,
                  descricao: String(r["descricao"] ?? ""),
                  ministrante: String(r["ministrantes"] ?? "Oficina entre equipes"),
                  local: roomName,
                  inicio: startIso,
                  fim: endIso,
                  vagas: roomObj?.capacidade ?? 25,
                  ativa: true,
                  created_at: new Date().toISOString(),
                });
              }
            }
          }
        }
        if (table === "reservations" && payload && typeof payload === "object") {
          const upd = payload as Record<string, unknown>;
          for (const r of matched) {
            const nextStatus = (upd["status"] ?? r["status"]) as string;
            const nextInicio = String(upd["inicio"] ?? r["inicio"]);
            const nextFim = String(upd["fim"] ?? r["fim"]);
            const nextRoom = String(upd["room_id"] ?? r["room_id"]);
            if (new Date(nextFim) <= new Date(nextInicio)) {
              return { data: null, error: { message: "O término deve ser após o início" } };
            }
            if (nextStatus === "approved") {
              const conflict = db.reservations.some(
                (other) =>
                  other.room_id === nextRoom &&
                  other.status === "approved" &&
                  other.id !== r["id"] &&
                  new Date(other.inicio) < new Date(nextFim) &&
                  new Date(other.fim) > new Date(nextInicio),
              );
              if (conflict) {
                return {
                  data: null,
                  error: { message: "Choque de horário com outra reserva aprovada nesta sala" },
                };
              }
            }
          }
        }
        matched.forEach((r) => Object.assign(r, payload));
        savePersistedDb(db);
        return { data: isMaybeSingle ? (matched[0] ?? null) : matched, error: null };
      }

      if (op === "delete") {
        for (const m of matched) {
          const idx = list.indexOf(m);
          if (idx !== -1) list.splice(idx, 1);
        }
        savePersistedDb(db);
        return { data: matched, error: null };
      }

      const result = [...matched];
      if (orderCol) {
        const col = orderCol;
        result.sort((a, b) => {
          const va = String(a[col] ?? "");
          const vb = String(b[col] ?? "");
          return orderAsc ? va.localeCompare(vb) : vb.localeCompare(va);
        });
      }
      return { data: isMaybeSingle ? (result[0] ?? null) : result, error: null };
    };

    const builder = {
      select: () => builder,
      insert: (values: unknown) => {
        op = "insert";
        payload = values;
        return builder;
      },
      update: (values: unknown) => {
        op = "update";
        payload = values;
        return builder;
      },
      delete: () => {
        op = "delete";
        return builder;
      },
      eq: (col: string, val: unknown) => {
        filters.push((r) => r[col] === val);
        return builder;
      },
      order: (col: string, opts?: { ascending?: boolean }) => {
        orderCol = col;
        orderAsc = opts?.ascending ?? true;
        return builder;
      },
      maybeSingle: () => {
        isMaybeSingle = true;
        return builder;
      },
      single: () => {
        isMaybeSingle = true;
        return builder;
      },
      then: <TResult1 = unknown, TResult2 = never>(
        onfulfilled?:
          | ((value: { data: unknown; error: null }) => TResult1 | PromiseLike<TResult1>)
          | null,
        onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
      ) => execute().then(onfulfilled, onrejected),
    };

    return builder;
  }

  return {
    from: (table: keyof TableMap) => buildQuery(table),
    rpc: async (fn: string, args?: Record<string, unknown>) => {
      if (fn === "room_busy" && args) {
        const room = String(args["_room"] ?? "");
        const from = new Date(String(args["_from"] ?? 0));
        const to = new Date(String(args["_to"] ?? Date.now() + 365 * dayMs));
        const busy = db.reservations
          .filter(
            (r) =>
              r.room_id === room &&
              r.status === "approved" &&
              new Date(r.inicio) < to &&
              new Date(r.fim) > from,
          )
          .map((r) => ({ inicio: r.inicio, fim: r.fim }));
        return { data: busy, error: null };
      }
      return { data: [], error: null };
    },
    auth: {
      getUser: async () => {
        currentUser = loadPersistedUser() ?? currentUser;
        return { data: { user: currentUser }, error: null };
      },
      getSession: async () => {
        currentUser = loadPersistedUser() ?? currentUser;
        return {
          data: {
            session: currentUser ? { user: currentUser, access_token: "mock-token" } : null,
          },
          error: null,
        };
      },
      signInWithPassword: async ({ email }: { email: string; password?: string }) => {
        const lower = email.toLowerCase();
        const req = db.leader_requests.find((r) => r.email.toLowerCase() === lower);
        if (req) {
          if (req.status === "pending") {
            return {
              data: { user: null, session: null },
              error: {
                message:
                  "Seu cadastro está aguardando aprovação do administrador. Você poderá entrar assim que for aprovado.",
              },
            };
          }
          if (req.status === "rejected") {
            const motivo = req.admin_note ? ` Motivo: ${req.admin_note}` : "";
            return {
              data: { user: null, session: null },
              error: {
                message: `Seu cadastro não foi aprovado pelo administrador.${motivo}`,
              },
            };
          }
        }

        const existingProfile = db.profiles.find((p) => p.email.toLowerCase() === lower);
        const existingRole = existingProfile
          ? db.user_roles.find((r) => r.user_id === existingProfile.id)?.role
          : undefined;
        const isAdmin = existingRole ? existingRole === "admin" : lower.includes("admin");
        const userId = existingProfile?.id ?? (isAdmin ? "user-admin-1" : "user-leader-1");
        const nome =
          existingProfile?.nome ?? (isAdmin ? "Administrador Ágora" : "Líder do GERM (UDESC)");

        if (!existingProfile) {
          db.profiles.push({
            id: userId,
            email,
            nome,
            created_at: new Date().toISOString(),
          });
        }
        if (!db.user_roles.some((r) => r.user_id === userId)) {
          db.user_roles.push({
            id: `role-${Date.now()}`,
            user_id: userId,
            role: isAdmin ? "admin" : "leader",
          });
        }
        savePersistedDb(db);

        currentUser = { id: userId, email, user_metadata: { nome } };
        savePersistedUser(currentUser);
        notify("SIGNED_IN");
        return {
          data: { user: currentUser, session: { user: currentUser, access_token: "mock-token" } },
          error: null,
        };
      },
      signUp: async ({
        email,
        options,
      }: {
        email: string;
        password?: string;
        options?: {
          data?: {
            nome?: string;
            faculdade?: string;
            projeto?: string;
            descricao?: string;
          };
        };
      }) => {
        const lower = email.toLowerCase();
        const existingReq = db.leader_requests.find((r) => r.email.toLowerCase() === lower);
        if (existingReq && existingReq.status === "pending") {
          return {
            data: { user: null, session: null },
            error: { message: "Já existe uma solicitação pendente para este e-mail." },
          };
        }

        const existing = db.profiles.find((p) => p.email.toLowerCase() === lower);
        const userId = existing?.id ?? `user-${Date.now()}`;
        const nome = options?.data?.nome || existing?.nome || email.split("@")[0] || "Líder";
        const faculdade = options?.data?.faculdade || "";
        const projeto = options?.data?.projeto || "";
        const descricao = options?.data?.descricao || "";

        if (!existing) {
          db.profiles.push({ id: userId, email, nome, created_at: new Date().toISOString() });
        }

        if (existingReq) {
          existingReq.nome_lider = nome;
          existingReq.faculdade = faculdade;
          existingReq.projeto = projeto;
          existingReq.descricao = descricao;
          existingReq.status = "pending";
          existingReq.admin_note = null;
        } else {
          db.leader_requests.push({
            id: `req-${Date.now()}`,
            user_id: userId,
            nome_lider: nome,
            email,
            faculdade,
            projeto,
            descricao,
            status: "pending",
            admin_note: null,
            created_at: new Date().toISOString(),
          });
        }

        savePersistedDb(db);
        // Não inicia sessão: aguarda aprovação do administrador
        return {
          data: {
            user: { id: userId, email, user_metadata: { nome, faculdade, projeto, descricao } },
            session: null,
          },
          error: null,
        };
      },
      signOut: async () => {
        currentUser = null;
        savePersistedUser(null);
        notify("SIGNED_OUT");
        return { error: null };
      },
      onAuthStateChange: (cb: (event: string, session: unknown) => void) => {
        listeners.add(cb);
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                listeners.delete(cb);
              },
            },
          },
        };
      },
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createHybridSupabaseClient(realUrl: string, realKey: string) {
  const realClient = createClient<Database>(realUrl, realKey, {
    global: {
      fetch: createSupabaseFetch(realKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  const mockClient = createMockSupabaseClient();

  const isLocalSessionActive = () => Boolean(loadPersistedUser());

  const hybridAuth = {
    getUser: async () => {
      if (isLocalSessionActive()) {
        return mockClient.auth.getUser();
      }
      const res = await realClient.auth.getUser();
      if (res.data?.user) return res;
      return mockClient.auth.getUser();
    },
    getSession: async () => {
      if (isLocalSessionActive()) {
        return mockClient.auth.getSession();
      }
      const res = await realClient.auth.getSession();
      if (res.data?.session) return res;
      return mockClient.auth.getSession();
    },
    signInWithPassword: async (creds: { email: string; password: string }) => {
      return mockClient.auth.signInWithPassword(creds);
    },
    signUp: async (creds: {
      email: string;
      password: string;
      options?: {
        emailRedirectTo?: string;
        data?: {
          nome?: string;
          faculdade?: string;
          projeto?: string;
          descricao?: string;
        };
      };
    }) => {
      return mockClient.auth.signUp(creds);
    },
    signOut: async () => {
      savePersistedUser(null);
      await mockClient.auth.signOut();
      try {
        await realClient.auth.signOut();
      } catch {
        // ignore
      }
      return { error: null };
    },
    onAuthStateChange: (cb: (event: any, session: any) => void) => {
      const sub1 = mockClient.auth.onAuthStateChange(cb);
      const sub2 = realClient.auth.onAuthStateChange(cb);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              sub1.data.subscription.unsubscribe();
              sub2.data.subscription.unsubscribe();
            },
          },
        },
      };
    },
  };

  return new Proxy(realClient, {
    get(_target, prop, receiver) {
      if (prop === "auth") {
        return hybridAuth;
      }
      return Reflect.get(mockClient, prop, receiver);
    },
  });
}

function createSupabaseClient() {
  const envMeta =
    typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env
      : ({} as Record<string, string | undefined>);
  const envProc =
    typeof process !== "undefined" && process.env
      ? process.env
      : ({} as Record<string, string | undefined>);
  const SUPABASE_URL = envMeta["VITE_SUPABASE_URL"] || envProc["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    envMeta["VITE_SUPABASE_PUBLISHABLE_KEY"] || envProc["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createMockSupabaseClient();
  }

  return createHybridSupabaseClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
