// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { SEED_PROJECTS } from "@/lib/seed-projects";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

type TableMap = {
  entities: Database["public"]["Tables"]["entities"]["Row"];
  events: Database["public"]["Tables"]["events"]["Row"];
  leader_requests: Database["public"]["Tables"]["leader_requests"]["Row"];
  members: Database["public"]["Tables"]["members"]["Row"];
  profiles: Database["public"]["Tables"]["profiles"]["Row"];
  reservations: Database["public"]["Tables"]["reservations"]["Row"];
  rooms: Database["public"]["Tables"]["rooms"]["Row"];
  user_roles: Database["public"]["Tables"]["user_roles"]["Row"];
};

const STORAGE_DB_KEY = "liga_uni_demo_db_v5";
const STORAGE_USER_KEY = "liga_uni_demo_user_v5";

function createInitialDb(): { [K in keyof TableMap]: TableMap[K][] } {
  const now = new Date().toISOString();
  const inDays = (days: number, hours: number) => {
    const d = new Date();
    d.setDate(d.getDate() + days);
    d.setHours(hours, 0, 0, 0);
    return d.toISOString();
  };

  return {
    profiles: [
      ...SEED_PROJECTS.map((p) => ({
        id: p.leaderId,
        nome: p.leaderNome,
        email: p.leaderEmail,
        created_at: now,
      })),
      {
        id: "user-admin-1",
        nome: "Administrador Ágora",
        email: "admin.teste@example.com",
        created_at: now,
      },
    ],
    user_roles: [
      ...SEED_PROJECTS.map((p, idx) => ({
        id: `role-leader-${idx + 1}`,
        user_id: p.leaderId,
        role: "leader" as const,
      })),
      { id: "role-admin-1", user_id: "user-admin-1", role: "admin" },
    ],
    entities: SEED_PROJECTS.map((p) => ({
      id: p.id,
      nome: p.nome,
      descricao: p.descricao,
      leader_id: p.leaderId,
      created_at: now,
    })),
    leader_requests: [
      {
        id: "req-1",
        user_id: "user-pending-1",
        nome_lider: "Mateus Henrique",
        email: "mateus.aero@edu.udesc.br",
        faculdade: "UDESC Joinville",
        projeto: "Liga Acadêmica de Engenharia Aeroespacial",
        descricao:
          "Grupo voltado ao estudo de propulsão, aerodinâmica e microssatélites no CCT/UDESC Joinville.",
        status: "pending",
        admin_note: null,
        created_at: now,
      },
    ],
    members: SEED_PROJECTS.flatMap((p) =>
      p.members.map((m) => ({
        id: m.id,
        entity_id: p.id,
        nome: m.nome,
        email: m.email,
        curso: m.curso,
        created_at: now,
      })),
    ),
    rooms: [
      {
        id: "room-1",
        nome: "Sala de reunião A (exemplo)",
        capacidade: 12,
        descricao: "Sala equipada com TV e quadro branco no Ágora Tech Park.",
        ativa: true,
        created_at: now,
      },
      {
        id: "room-2",
        nome: "Sala de reunião B (exemplo)",
        capacidade: 20,
        descricao: "Espaço colaborativo para dinâmicas e reuniões de projetos.",
        ativa: true,
        created_at: now,
      },
      {
        id: "room-3",
        nome: "Auditório Ágora (exemplo)",
        capacidade: 80,
        descricao: "Auditório para capacitações, workshops e hackathons.",
        ativa: true,
        created_at: now,
      },
    ],
    events: [
      {
        id: "ev-1",
        entity_id: "ent-1",
        titulo: "Oficina de Robótica Móvel e Inclusão Social",
        descricao:
          "Atividade prática do GERM aberta à comunidade para fomentar o interesse em ciência e tecnologia.",
        local: "Sala de reunião A (exemplo)",
        inicio: inDays(2, 14),
        fim: inDays(2, 16),
        created_at: now,
      },
      {
        id: "ev-2",
        entity_id: "ent-1",
        titulo: "Mostra e Hackathon de Robótica no Ágora",
        descricao:
          "Imersão de dois dias com discentes do CCT/UDESC apresentando projetos de robótica móvel.",
        local: "Auditório Ágora (exemplo)",
        inicio: inDays(5, 9),
        fim: inDays(6, 18),
        created_at: now,
      },
      {
        id: "ev-3",
        entity_id: "ent-1",
        titulo: "Reunião Geral do GERM — UDESC Joinville",
        descricao:
          "Alinhamento das frentes de ensino, pesquisa e extensão dos cursos do Centro de Ciências Tecnológicas.",
        local: "Sala de reunião B (exemplo)",
        inicio: inDays(10, 19),
        fim: inDays(10, 21),
        created_at: now,
      },
      {
        id: "ev-4",
        entity_id: "ent-2",
        titulo: "Apresentação dos Protótipos IC e EV — Fórmula CEM",
        descricao:
          "Demonstração técnica dos veículos Fórmula-SAE a combustão e elétrico desenvolvidos na UFSC Joinville.",
        local: "Auditório Ágora (exemplo)",
        inicio: inDays(4, 15),
        fim: inDays(4, 18),
        created_at: now,
      },
      {
        id: "ev-5",
        entity_id: "ent-2",
        titulo: "Revisão de Projeto para Competição SAE Brasil",
        descricao:
          "Reunião dos subsistemas de powertrain, aerodinâmica e eletrônica da equipe Fórmula CEM.",
        local: "Sala de reunião B (exemplo)",
        inicio: inDays(8, 14),
        fim: inDays(8, 17),
        created_at: now,
      },
    ],
    reservations: [
      {
        id: "res-1",
        entity_id: "ent-1",
        event_id: "ev-1",
        room_id: "room-1",
        requested_by: "user-leader-1",
        motivo: "Realização da Oficina de Robótica Móvel e Inclusão Social pelo GERM (UDESC)",
        inicio: inDays(2, 14),
        fim: inDays(2, 16),
        status: "approved",
        admin_note: null,
        created_at: now,
      },
      {
        id: "res-2",
        entity_id: "ent-1",
        event_id: "ev-3",
        room_id: "room-2",
        requested_by: "user-leader-1",
        motivo: "Reunião Geral da equipe do GERM — UDESC Joinville",
        inicio: inDays(10, 19),
        fim: inDays(10, 21),
        status: "pending",
        admin_note: null,
        created_at: now,
      },
      {
        id: "res-3",
        entity_id: "ent-2",
        event_id: "ev-4",
        room_id: "room-3",
        requested_by: "user-leader-2",
        motivo: "Apresentação dos Protótipos IC e EV da Fórmula CEM (UFSC Joinville)",
        inicio: inDays(4, 15),
        fim: inDays(4, 18),
        status: "approved",
        admin_note: null,
        created_at: now,
      },
      {
        id: "res-4",
        entity_id: "ent-2",
        event_id: "ev-5",
        room_id: "room-2",
        requested_by: "user-leader-2",
        motivo: "Revisão de Projeto para Competição SAE Brasil — Fórmula CEM (UFSC)",
        inicio: inDays(8, 14),
        fim: inDays(8, 17),
        status: "pending",
        admin_note: null,
        created_at: now,
      },
    ],
  };
}

function loadPersistedDb(): { [K in keyof TableMap]: TableMap[K][] } {
  if (typeof window !== "undefined") {
    try {
      const raw = window.localStorage.getItem(STORAGE_DB_KEY);
      if (raw) {
        return JSON.parse(raw) as { [K in keyof TableMap]: TableMap[K][] };
      }
    } catch {
      // ignore
    }
  }
  const initial = createInitialDb();
  savePersistedDb(initial);
  return initial;
}

function savePersistedDb(db: { [K in keyof TableMap]: TableMap[K][] }) {
  if (typeof window !== "undefined") {
    try {
      window.localStorage.setItem(STORAGE_DB_KEY, JSON.stringify(db));
    } catch {
      // ignore
    }
  }
}

type DemoUser = { id: string; email: string; user_metadata?: Record<string, unknown> };

function loadPersistedUser(): DemoUser | null {
  if (typeof window !== "undefined") {
    try {
      const raw = window.localStorage.getItem(STORAGE_USER_KEY);
      if (raw) return JSON.parse(raw) as DemoUser;
    } catch {
      // ignore
    }
  }
  return null;
}

function savePersistedUser(user: DemoUser | null) {
  if (typeof window !== "undefined") {
    try {
      if (user) window.localStorage.setItem(STORAGE_USER_KEY, JSON.stringify(user));
      else window.localStorage.removeItem(STORAGE_USER_KEY);
    } catch {
      // ignore
    }
  }
}

function createMockSupabaseClient() {
  const dayMs = 86400000;
  const db = loadPersistedDb();
  let currentUser: DemoUser | null = loadPersistedUser();
  const listeners = new Set<(event: string, session: unknown) => void>();

  function notify(event: string) {
    const session = currentUser ? { user: currentUser, access_token: "mock-token" } : null;
    listeners.forEach((cb) => cb(event, session));
  }

  function buildQuery(table: keyof TableMap) {
    const filters: Array<(row: Record<string, unknown>) => boolean> = [];
    let orderCol: string | null = null;
    let orderAsc = true;
    let op: "select" | "insert" | "update" | "delete" = "select";
    let payload: unknown = null;
    let isMaybeSingle = false;

    const execute = async () => {
      const list = db[table] as Record<string, unknown>[];
      if (op === "insert") {
        const items = Array.isArray(payload) ? payload : [payload];
        const inserted = items.map((item) => {
          const row = {
            id: `${table}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
            created_at: new Date().toISOString(),
            ...(table === "reservations" ? { status: "pending", admin_note: null } : {}),
            ...(item as Record<string, unknown>),
          };
          list.push(row);
          return row;
        });
        savePersistedDb(db);
        return { data: isMaybeSingle ? (inserted[0] ?? null) : inserted, error: null };
      }

      const matched = list.filter((r) => filters.every((f) => f(r)));

      if (op === "update") {
        if (table === "leader_requests" && payload && typeof payload === "object") {
          const upd = payload as Record<string, unknown>;
          for (const r of matched) {
            const nextStatus = (upd["status"] ?? r["status"]) as string;
            const reqUserId = String(r["user_id"]);
            const reqNome = String(r["nome_lider"]);
            const reqEmail = String(r["email"]);
            const reqFaculdade = String(r["faculdade"]);
            const reqProjeto = String(r["projeto"]);
            const reqDescricao = String(r["descricao"] ?? "");

            if (nextStatus === "approved") {
              if (!db.profiles.some((p) => p.id === reqUserId)) {
                db.profiles.push({
                  id: reqUserId,
                  nome: reqNome,
                  email: reqEmail,
                  created_at: new Date().toISOString(),
                });
              }
              if (!db.user_roles.some((ur) => ur.user_id === reqUserId)) {
                db.user_roles.push({
                  id: `role-${Date.now()}`,
                  user_id: reqUserId,
                  role: "leader",
                });
              }
              if (!db.entities.some((ent) => ent.leader_id === reqUserId)) {
                const entityName = reqFaculdade
                  ? `${reqProjeto} (${reqFaculdade})`
                  : reqProjeto;
                db.entities.push({
                  id: `ent-${Date.now()}`,
                  nome: entityName,
                  descricao: reqDescricao,
                  leader_id: reqUserId,
                  created_at: new Date().toISOString(),
                });
              }
            }
          }
        }
        if (table === "reservations" && payload && typeof payload === "object") {
          const upd = payload as Record<string, unknown>;
          for (const r of matched) {
            const nextStatus = (upd["status"] ?? r["status"]) as string;
            const nextInicio = String(upd["inicio"] ?? r["inicio"]);
            const nextFim = String(upd["fim"] ?? r["fim"]);
            const nextRoom = String(upd["room_id"] ?? r["room_id"]);
            if (new Date(nextFim) <= new Date(nextInicio)) {
              return { data: null, error: { message: "O término deve ser após o início" } };
            }
            if (nextStatus === "approved") {
              const conflict = db.reservations.some(
                (other) =>
                  other.room_id === nextRoom &&
                  other.status === "approved" &&
                  other.id !== r["id"] &&
                  new Date(other.inicio) < new Date(nextFim) &&
                  new Date(other.fim) > new Date(nextInicio),
              );
              if (conflict) {
                return {
                  data: null,
                  error: { message: "Choque de horário com outra reserva aprovada nesta sala" },
                };
              }
            }
          }
        }
        matched.forEach((r) => Object.assign(r, payload));
        savePersistedDb(db);
        return { data: isMaybeSingle ? (matched[0] ?? null) : matched, error: null };
      }

      if (op === "delete") {
        for (const m of matched) {
          const idx = list.indexOf(m);
          if (idx !== -1) list.splice(idx, 1);
        }
        savePersistedDb(db);
        return { data: matched, error: null };
      }

      const result = [...matched];
      if (orderCol) {
        const col = orderCol;
        result.sort((a, b) => {
          const va = String(a[col] ?? "");
          const vb = String(b[col] ?? "");
          return orderAsc ? va.localeCompare(vb) : vb.localeCompare(va);
        });
      }
      return { data: isMaybeSingle ? (result[0] ?? null) : result, error: null };
    };

    const builder = {
      select: () => builder,
      insert: (values: unknown) => {
        op = "insert";
        payload = values;
        return builder;
      },
      update: (values: unknown) => {
        op = "update";
        payload = values;
        return builder;
      },
      delete: () => {
        op = "delete";
        return builder;
      },
      eq: (col: string, val: unknown) => {
        filters.push((r) => r[col] === val);
        return builder;
      },
      order: (col: string, opts?: { ascending?: boolean }) => {
        orderCol = col;
        orderAsc = opts?.ascending ?? true;
        return builder;
      },
      maybeSingle: () => {
        isMaybeSingle = true;
        return builder;
      },
      single: () => {
        isMaybeSingle = true;
        return builder;
      },
      then: <TResult1 = unknown, TResult2 = never>(
        onfulfilled?:
          | ((value: { data: unknown; error: null }) => TResult1 | PromiseLike<TResult1>)
          | null,
        onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
      ) => execute().then(onfulfilled, onrejected),
    };

    return builder;
  }

  return {
    from: (table: keyof TableMap) => buildQuery(table),
    rpc: async (fn: string, args?: Record<string, unknown>) => {
      if (fn === "room_busy" && args) {
        const room = String(args["_room"] ?? "");
        const from = new Date(String(args["_from"] ?? 0));
        const to = new Date(String(args["_to"] ?? Date.now() + 365 * dayMs));
        const busy = db.reservations
          .filter(
            (r) =>
              r.room_id === room &&
              r.status === "approved" &&
              new Date(r.inicio) < to &&
              new Date(r.fim) > from,
          )
          .map((r) => ({ inicio: r.inicio, fim: r.fim }));
        return { data: busy, error: null };
      }
      return { data: [], error: null };
    },
    auth: {
      getUser: async () => {
        currentUser = loadPersistedUser() ?? currentUser;
        return { data: { user: currentUser }, error: null };
      },
      getSession: async () => {
        currentUser = loadPersistedUser() ?? currentUser;
        return {
          data: {
            session: currentUser ? { user: currentUser, access_token: "mock-token" } : null,
          },
          error: null,
        };
      },
      signInWithPassword: async ({ email }: { email: string; password?: string }) => {
        const lower = email.toLowerCase();
        const req = db.leader_requests.find((r) => r.email.toLowerCase() === lower);
        if (req) {
          if (req.status === "pending") {
            return {
              data: { user: null, session: null },
              error: {
                message:
                  "Seu cadastro está aguardando aprovação do administrador. Você poderá entrar assim que for aprovado.",
              },
            };
          }
          if (req.status === "rejected") {
            const motivo = req.admin_note ? ` Motivo: ${req.admin_note}` : "";
            return {
              data: { user: null, session: null },
              error: {
                message: `Seu cadastro não foi aprovado pelo administrador.${motivo}`,
              },
            };
          }
        }

        const existingProfile = db.profiles.find((p) => p.email.toLowerCase() === lower);
        const isAdmin = lower.includes("admin");
        const userId = existingProfile?.id ?? (isAdmin ? "user-admin-1" : "user-leader-1");
        const nome =
          existingProfile?.nome ?? (isAdmin ? "Administrador Ágora" : "Líder do GERM (UDESC)");

        if (!existingProfile) {
          db.profiles.push({
            id: userId,
            email,
            nome,
            created_at: new Date().toISOString(),
          });
        }
        if (!db.user_roles.some((r) => r.user_id === userId)) {
          db.user_roles.push({
            id: `role-${Date.now()}`,
            user_id: userId,
            role: isAdmin ? "admin" : "leader",
          });
        }
        savePersistedDb(db);

        currentUser = { id: userId, email, user_metadata: { nome } };
        savePersistedUser(currentUser);
        notify("SIGNED_IN");
        return {
          data: { user: currentUser, session: { user: currentUser, access_token: "mock-token" } },
          error: null,
        };
      },
      signUp: async ({
        email,
        options,
      }: {
        email: string;
        password?: string;
        options?: {
          data?: {
            nome?: string;
            faculdade?: string;
            projeto?: string;
            descricao?: string;
          };
        };
      }) => {
        const lower = email.toLowerCase();
        const existingReq = db.leader_requests.find((r) => r.email.toLowerCase() === lower);
        if (existingReq && existingReq.status === "pending") {
          return {
            data: { user: null, session: null },
            error: { message: "Já existe uma solicitação pendente para este e-mail." },
          };
        }

        const existing = db.profiles.find((p) => p.email.toLowerCase() === lower);
        const userId = existing?.id ?? `user-${Date.now()}`;
        const nome = options?.data?.nome || existing?.nome || email.split("@")[0] || "Líder";
        const faculdade = options?.data?.faculdade || "";
        const projeto = options?.data?.projeto || "";
        const descricao = options?.data?.descricao || "";

        if (!existing) {
          db.profiles.push({ id: userId, email, nome, created_at: new Date().toISOString() });
        }

        if (existingReq) {
          existingReq.nome_lider = nome;
          existingReq.faculdade = faculdade;
          existingReq.projeto = projeto;
          existingReq.descricao = descricao;
          existingReq.status = "pending";
          existingReq.admin_note = null;
        } else {
          db.leader_requests.push({
            id: `req-${Date.now()}`,
            user_id: userId,
            nome_lider: nome,
            email,
            faculdade,
            projeto,
            descricao,
            status: "pending",
            admin_note: null,
            created_at: new Date().toISOString(),
          });
        }

        savePersistedDb(db);
        // Não inicia sessão: aguarda aprovação do administrador
        return {
          data: {
            user: { id: userId, email, user_metadata: { nome, faculdade, projeto, descricao } },
            session: null,
          },
          error: null,
        };
      },
      signOut: async () => {
        currentUser = null;
        savePersistedUser(null);
        notify("SIGNED_OUT");
        return { error: null };
      },
      onAuthStateChange: (cb: (event: string, session: unknown) => void) => {
        listeners.add(cb);
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                listeners.delete(cb);
              },
            },
          },
        };
      },
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createHybridSupabaseClient(realUrl: string, realKey: string) {
  const realClient = createClient<Database>(realUrl, realKey, {
    global: {
      fetch: createSupabaseFetch(realKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  const mockClient = createMockSupabaseClient();

  const isLocalSessionActive = () => Boolean(loadPersistedUser());

  const hybridAuth = {
    getUser: async () => {
      if (isLocalSessionActive()) {
        return mockClient.auth.getUser();
      }
      const res = await realClient.auth.getUser();
      if (res.data?.user) return res;
      return mockClient.auth.getUser();
    },
    getSession: async () => {
      if (isLocalSessionActive()) {
        return mockClient.auth.getSession();
      }
      const res = await realClient.auth.getSession();
      if (res.data?.session) return res;
      return mockClient.auth.getSession();
    },
    signInWithPassword: async (creds: { email: string; password: string }) => {
      return mockClient.auth.signInWithPassword(creds);
    },
    signUp: async (creds: {
      email: string;
      password: string;
      options?: {
        emailRedirectTo?: string;
        data?: {
          nome?: string;
          faculdade?: string;
          projeto?: string;
          descricao?: string;
        };
      };
    }) => {
      return mockClient.auth.signUp(creds);
    },
    signOut: async () => {
      savePersistedUser(null);
      await mockClient.auth.signOut();
      try {
        await realClient.auth.signOut();
      } catch {
        // ignore
      }
      return { error: null };
    },
    onAuthStateChange: (cb: (event: any, session: any) => void) => {
      const sub1 = mockClient.auth.onAuthStateChange(cb);
      const sub2 = realClient.auth.onAuthStateChange(cb);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              sub1.data.subscription.unsubscribe();
              sub2.data.subscription.unsubscribe();
            },
          },
        },
      };
    },
  };

  return new Proxy(realClient, {
    get(target, prop, receiver) {
      if (prop === "auth") {
        return hybridAuth;
      }
      if (isLocalSessionActive()) {
        return Reflect.get(mockClient, prop, receiver);
      }
      return Reflect.get(target, prop, receiver);
    },
  });
}

function createSupabaseClient() {
  const envMeta =
    typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env
      : ({} as Record<string, string | undefined>);
  const envProc =
    typeof process !== "undefined" && process.env
      ? process.env
      : ({} as Record<string, string | undefined>);
  const SUPABASE_URL = envMeta["VITE_SUPABASE_URL"] || envProc["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    envMeta["VITE_SUPABASE_PUBLISHABLE_KEY"] || envProc["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createMockSupabaseClient();
  }

  return createHybridSupabaseClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
